apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      app: demo-go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-go-app
    spec:
      containers:
      - name: test-app
        image: alex43/go-demo-app:v2.0
        ports:
        - containerPort: 8080
